CHROMEOS: kernelconfig: rewrite style
This makes it use functions which are easier to read/manage.
Also change variable brace style.

BUG=None
TEST=`./chromeos/scripts/kernelconfig oldconfig` still works
Signed-off-by: Mike Frysinger <vapier@chromium.org>

Change-Id: I19258417036cfe851b896e98030d93fbd7ea8e9b
Reviewed-on: https://chromium-review.googlesource.com/188628
Reviewed-by: Olof Johansson <olofj@chromium.org>
Commit-Queue: Mike Frysinger <vapier@chromium.org>
Tested-by: Mike Frysinger <vapier@chromium.org>

diff --git a/chromeos/scripts/kernelconfig b/chromeos/scripts/kernelconfig
--- a/chromeos/scripts/kernelconfig
+++ b/chromeos/scripts/kernelconfig
@@ -1,95 +1,98 @@
 #!/bin/bash
-
 # Script to merge all configs and run 'make silentoldconfig' on it to wade out bad juju.
 # Then split the configs into distro-commmon and flavour-specific parts
 #
 # See this page for more details:
 # http://dev.chromium.org/chromium-os/how-tos-and-troubleshooting/kernel-configuration
 
-# We have to be in the top level kernel source directory
-if [ ! -f MAINTAINERS ] || [ ! -f Makefile ]; then
-	echo "This does not appear to be the kernel source directory." 1>&2
+error() {
+	printf 'error: %b\n' "$*" >&2
+}
+
+die() {
+	error "$@"
 	exit 1
-fi
+}
 
-mode=${1:?"Usage: $0 [oldconfig|editconfig]"}
-case "${mode}" in
-    oldconfig)  ;; # All is good
-    editconfig) ;; # All is good
-    genconfig)  ;; # All is good
-    *) echo "$0 called with invalid mode" 1>&2
-       exit 1 ;;
-esac
-kerneldir="`pwd`"
-confdir="${kerneldir}/chromeos/config"
-archs="x86_64 i386 armel"
-bindir="`pwd`/chromeos/scripts"
-base_conf="${confdir}/base.config"
-tmpdir=`mktemp -d`
+usage() {
+	cat <<-EOF
+	Usage: ${0##*/} [options] <oldconfig|editconfig|genconfig>
 
-if [ "${mode}" = "genconfig" ]; then
-	keep=1
-	mode="oldconfig"
-	test -d CONFIGS || mkdir CONFIGS
-fi
+	Options:
+	  -h   This screen.
+	EOF
 
-test -d build || mkdir build
+	if [[ $# -gt 0 ]]; then
+		echo
+		die "$@"
+	else
+		exit 0
+	fi
+}
 
-for arch in ${archs}; do
-	# Map debian archs to kernel archs
+build_one() {
+	local arch=$1
+	local kernarch
+
+	# Map debian archs to kernel archs.
 	case "${arch}" in
-		amd64)	kernarch="x86_64"	;;
-		lpia)   kernarch="x86" ;;
-		sparc)	kernarch="sparc64"	;;
-		armel)  kernarch="arm" ;;
-		*)	kernarch="${arch}"	;;
+	armel) kernarch="arm" ;;
+	*)     kernarch="${arch}" ;;
 	esac
 
 	echo ""
 	echo "***************************************"
 	echo "* Processing ${arch} (${kernarch}) ... "
-	archconfdir=${confdir}/${arch}
-	flavourconfigs=$(cd ${archconfdir} && ls *.flavour.config)
+
+	local O="$(pwd)/build/${arch}"
+	mkdir -p "${O}"
+
+	local config
+	local archconfdir="${confdir}/${arch}"
+	local flavourconfigs=( $(cd "${archconfdir}" && echo *.flavour.config) )
 
 	# Merge configs
 	# We merge base.config + common.config + <flavour>.flavour.config
 
-	for config in ${flavourconfigs}; do
-		fullconf="${tmpdir}/${arch}-${config}-full"
-		cp ${base_conf} "${fullconf}"
-		cat ${archconfdir}/common.config >> "${fullconf}"
-		cat ${archconfdir}/${config} >> "${fullconf}"
-	done
-
-	for config in ${flavourconfigs}; do
-		fullconf="${tmpdir}/${arch}-${config}-full"
-		mv "${fullconf}" build/.config
+	for config in "${flavourconfigs[@]}"; do
+		cat \
+			"${base_conf}" \
+			"${archconfdir}/common.config" \
+			"${archconfdir}/${config}" \
+			> "${O}/.config"
 		# Call oldconfig or menuconfig
-		case "${mode}" in
-		    oldconfig)
+		case ${mode} in
+		oldconfig)
 			# Weed out incorrect config parameters
 			echo "* Run silentoldconfig on ${arch}/${config} ..."
-			make O=`pwd`/build ARCH=${kernarch} silentoldconfig ;;
-		    editconfig)
+			make -j O="${O}" ARCH=${kernarch} silentoldconfig
+			;;
+		editconfig)
 			# Interactively edit config parameters
 			echo "* ${arch}/${config}: press <Enter> to edit, S to skip"
 			read -s -n 1
-			if [ ${REPLY} = 's' -o ${REPLY} = 'S' ]; then
-			    echo "* Skip: running silentoldconfig"
-			    make O=`pwd`/build ARCH=${kernarch} silentoldconfig
-			else
-			    echo "* Running menuconfig"
-			    make O=`pwd`/build ARCH=${kernarch} menuconfig
-			fi ;;
-		    *)  # Bad!
-			exit 1 ;;
+			case ${REPLY} in
+			s|S)
+				echo "* Skip: running silentoldconfig"
+				make -j O="${O}" ARCH=${kernarch} silentoldconfig
+				;;
+			*)
+				echo "* Running menuconfig"
+				make -j O="${O}" ARCH=${kernarch} menuconfig
+				;;
+			esac
+			;;
+		*)	# Bad!
+			die "invalid mode ${mode}"
+			;;
 		esac
-		cat build/.config > ${archconfdir}/${config}
-		if [ "${keep}" = "1" ]; then
-			make O=`pwd`/build ARCH=${kernarch} oldconfig
-			make O=`pwd`/build ARCH=${kernarch} savedefconfig
-			mv build/.config CONFIGS/${arch}-${config}
-			mv build/defconfig CONFIGS/${arch}-${config}.def
+
+		cat "${O}/.config" > "${archconfdir}/${config}"
+		if [[ "${keep}" == "1" ]]; then
+			make -j O="${O}" ARCH=${kernarch} oldconfig
+			make -j O="${O}" ARCH=${kernarch} savedefconfig
+			mv "${O}"/.config "CONFIGS/${arch}-${config}"
+			mv "${O}"/defconfig "CONFIGS/${arch}-${config}.def"
 		fi
 	done
 
@@ -99,16 +102,85 @@ for arch in ${archs}; do
 	# Can we make this more robust by avoiding $tmpdir completely?
 	# This approach was used for now because I didn't want to change
 	# splitconfig
-	(cd ${archconfdir}; rm common.config; ${bindir}/splitconfig; \
-	    mv common.config ${tmpdir}/${arch}.config)
-done
+	pushd "${archconfdir}" >/dev/null
+	rm common.config
+	"${bindir}/splitconfig"
+	mv common.config "${tmpdir}/${arch}.config"
+	popd >/dev/null
+}
 
-# Now run splitconfig on all the <arch>.common.config copied to
-# $tmpdir
-(cd ${tmpdir}; ${bindir}/splitconfig)
-mv ${tmpdir}/common.config ${base_conf}
-for arch in ${archs}; do
-	mv ${tmpdir}/${arch}.config ${confdir}/${arch}/common.config
-done
+cleanup() {
+	rm -rf "${tmpdir}"
+}
 
-rm -rf ${tmpdir}
+cd_kerneldir() {
+	# We have to be in the top level kernel source directory.
+	if [[ ! -f MAINTAINERS || ! -f Makefile ]]; then
+		# See if we can find it automatically first.
+		local d=$(realpath "${0%/*}/../..")
+		cd "${d}"
+		if [[ ! -f MAINTAINERS || ! -f Makefile ]]; then
+			die "This does not appear to be the kernel source directory."
+		else
+			echo "Using top kernel dir: ${d}"
+		fi
+	fi
+}
+
+main() {
+	# Process use flags first (so -h works nicely).
+	local opt
+	while getopts "h" opt; do
+		case ${opt} in
+		h) usage ;;
+		*) usage "Invalid option ${opt}" ;;
+		esac
+	done
+	shift $(( OPTIND - 1 ))
+
+	# Process the remaining args.
+	local mode=$1
+	case ${mode} in
+	oldconfig)  ;; # All is good
+	editconfig) ;; # All is good
+	genconfig)  ;; # All is good
+	*) usage "invalid/missing mode: ${mode}" ;;
+	esac
+
+	# Then make sure we're in the right directory.
+	cd_kerneldir
+
+	# Set up variables the build func expects.
+	local kerneldir=$(pwd)
+	local confdir="${kerneldir}/chromeos/config"
+	local archs=( x86_64 i386 armel )
+	local bindir="${kerneldir}/chromeos/scripts"
+	local base_conf="${confdir}/base.config"
+
+	export tmpdir=$(mktemp -d)
+	trap cleanup EXIT
+
+	local keep=0
+	if [[ "${mode}" == "genconfig" ]]; then
+		keep=1
+		mode="oldconfig"
+		mkdir -p CONFIGS
+	fi
+
+	mkdir -p build
+
+	echo "running ${mode} for ${archs[*]}"
+	echo ""
+	for arch in "${archs[@]}"; do
+		build_one "${arch}"
+	done
+
+	# Now run splitconfig on all the <arch>.common.config copied to $tmpdir.
+	pushd "${tmpdir}" >/dev/null
+	"${bindir}/splitconfig"
+	mv "common.config" "${base_conf}"
+	for arch in "${archs[@]}"; do
+		mv "${arch}.config" "${confdir}/${arch}/common.config"
+	done
+}
+main "$@"
